### ISSUE TITLE
"Disabling Domain Reloading" not working

### ISSUE THREAD

**Issue by if1live** [codewriter-packages/UniMob#15]
**Describe the bug**

[Enter Play Mode faster in Unity 2019.3
](https://blog.unity.com/technology/enter-play-mode-faster-in-unity-2019-3)

1. Project Settings -> Editor -> Enter Play Mode Option (true)
2. first play: "AtomScheduler" object created. UniMob working well
3. stop play mode.
4. second play: "AtomScheduler" object not created. UniMob not working

**Expected behavior**

When "Disabling Domain Reloading", AtomScheduler should be created.
static variable should be cleared.
https://github.com/codewriter-packages/UniMob/blob/59a60bbdd6630d6869858a703a7803bb30ccb46a/Runtime/Core/AtomScheduler.cs#L21

maybe this document useful.
[unity document for Domain Reloading](https://docs.unity3d.com/2019.3/Documentation/Manual/DomainReloading.html)

**Desktop:** 
**Unity version:** 
**UniMob version:** 59a60bbdd6630d6869858a703a7803bb30ccb46a
**Other plugins installed:**

**Comment by vanifatovvlad** [comment]
I added Domain Reload support in a [domain-reload-support](https://github.com/codewriter-packages/UniMob/tree/domain-reload-support) branch. Can you check it works correctly in your project?

**Comment by if1live** [comment]
your code works well. 👍 

note: my solution
https://github.com/5minlab/UniMob/commit/98bbbea86bbc611e721e7247e260af37c5c9ff63
Actually, AtomScheduler is singleton. So I use OnDestroy to reset static variable.
