### ISSUE TITLE
Package name should conform to reverse domain name notation with at least 3 components

### ISSUE THREAD

**Issue by laicasaane** [codewriter-packages/UniMob#9]
Please correct the package name to include at least 3 components, e.g. `com.unity.ugui`.
I want to add your packages to OpenUPM, but it requires the package to have a valid name format.

I suggest adding `codewriter` to the name, so `com.unimob` will become `'com.codewriter.unimob`.

**Comment by vanifatovvlad** [comment]
Changed the package name to `com.codewriter.unimob`
